# Generated by Django 5.0.1 on 2025-04-23 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_survey', models.DateField(auto_now_add=True)),
                ('liked_students', models.BooleanField(default=False)),
                ('liked_location', models.BooleanField(default=False)),
                ('liked_campus', models.BooleanField(default=False)),
                ('liked_atmosphere', models.BooleanField(default=False)),
                ('liked_dorm_rooms', models.BooleanField(default=False)),
                ('liked_sports', models.BooleanField(default=False)),
                ('interest_source', models.CharField(choices=[('friends', 'Friends'), ('television', 'Television'), ('internet', 'Internet'), ('other', 'Other')], max_length=20)),
                ('recommendation_likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
